---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/Kavan-Dalwadi/app-fluxCD
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev
